#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"


Mailman::Application.run do
  default do
    Ticket.create! subject: message.subject, body: message.body.decoded, from: message.from.first
  end
end
