#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"


Mailman.config.pop3 = {
  server: 'pop.gmail.com', port: 995, ssl: true,
  username: ENV["GMAIL_USERNAME"],
  password: ENV["GMAIL_PASSWORD"]
}

Mailman::Application.run do
  default do
    Ticket.receive_mail(message)
  end  
end
